version: '3.8'
services:
  # 1. Spring Boot 애플리케이션 서비스
  app:
    build: . # 현재 폴더의 Dockerfile을 사용하여 이미지를 빌드
    container_name: spring_app_finnote
    ports:
      - "8080:8080"
    environment:
      # DB 접속 설정
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/finnote_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db # db 서비스가 먼저 시작되도록 설정

  # 2. PostgreSQL 데이터베이스 서비스
  db:
    image: postgres:14-alpine
    container_name: postgres_db_finnote
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finnote_db
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql # 이니셜 스크립트 위치
volumes:
  postgres_data: